### ISSUE TITLE
Can't use headless in Linux with Chrome

### ISSUE THREAD

**Issue by anstarword** [undera/jmeter-plugins-webdriver#2]
Hi,
When i enable chrome headless and run the jmeter script, i receive below error:
java.lang.NoSuchMethodError: org.openqa.selenium.chrome.ChromeOptions.addArguments([Ljava/lang/String;)Lorg/openqa/selenium/chrome/ChromeOptions;

Do you have idea about this?
My Chrome version and Chrome webdriver version is matched.
Chrome: google-chrome-73.0.3683.103
chromedriver: 73.0.3683.68

**Comment by anstarword** [comment]
Selenium library version 3.14.0
Jmeter: 4.0

**Comment by undera** [comment]
Sorry, the right place to raise issues is mailing list
